export const products = [
    {
        id: 1,
        name: 'Tomatoes',
        img: 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=600',
        price: 2.5,
        rating: 4.5,
        deliveryTime: '2 days',
        description: 'Fresh and juicy tomatoes perfect for salads and cooking.',
        plantingProcess: 'Plant seeds indoors 6-8 weeks before the last frost. Transplant outdoors after the danger of frost has passed, spacing plants 18-24 inches apart.',
        nutrition: 'Rich in vitamins C, K, and potassium; low in calories.',
        detailedDescription: 'Tomatoes are a versatile fruit used in a variety of dishes, from salads to sauces. They thrive in warm climates and require full sun for optimal growth. Regular watering and staking may be necessary to support the plants as they grow.'
    },
    {
        id: 2,
        name: 'Potatoes',
        img: 'https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg?auto=compress&cs=tinysrgb&w=600',
        price: 1.8,
        rating: 4.2,
        deliveryTime: '3 days',
        description: 'Versatile potatoes ideal for baking, frying, and mashing.',
        plantingProcess: 'Plant seed potatoes in early spring, 4 inches deep and 12 inches apart in rows. Hill soil around the plants as they grow.',
        nutrition: 'High in carbohydrates, vitamin C, and potassium.',
        detailedDescription: 'Potatoes are a staple food around the world, known for their versatility and nutritional value. They can be prepared in numerous ways—boiled, baked, fried, or mashed—and are rich in essential nutrients. Potatoes prefer well-drained soil and consistent moisture.'
    },
    {
        id: 3,
        name: 'Carrots',
        img: 'https://images.pexels.com/photos/1297256/pexels-photo-1297256.jpeg?auto=compress&cs=tinysrgb&w=600',
        price: 2.0,
        rating: 4.3,
        deliveryTime: '2 days',
        description: 'Crunchy and sweet carrots, great for snacking and cooking.',
        plantingProcess: 'Sow seeds directly in the ground in early spring or late summer. Thin seedlings to 2-3 inches apart once they are a few inches tall.',
        nutrition: 'High in beta-carotene, fiber, vitamin K1, potassium, and antioxidants.',
        detailedDescription: 'Carrots are root vegetables that come in various colors including orange, purple, and yellow. They are rich in beta-carotene which is converted into vitamin A in the body. Carrots can be eaten raw or cooked and are often used in salads, soups, and stews.'
    },
    {
        id: 4,
        name: 'Cabbage',
        img: 'https://images.pexels.com/photos/257259/pexels-photo-257259.jpeg?auto=compress&cs=tinysrgb&w=600',
        price: 1.5,
        rating: 4.0,
        deliveryTime: '4 days',
        description: 'Fresh cabbage, perfect for salads, slaws, and stir-fries.',
        plantingProcess: 'Start seeds indoors or sow directly outdoors in early spring or late summer. Space plants about 18 inches apart.',
        nutrition: 'Rich in vitamins C and K; low in calories.',
        detailedDescription: 'Cabbage is a leafy green vegetable that can be eaten raw or cooked. It is often used in salads like coleslaw or as a filling for various dishes. Cabbage is known for its high vitamin C content and is beneficial for digestive health.'
    },
    {
        id: 5,
        name: 'Onions',
        img: 'https://images.pexels.com/photos/175415/pexels-photo-175415.jpeg?auto=compress&cs=tinysrgb&w=600',
        price: 1.2,
        rating: 4.1,
        deliveryTime: '3 days',
        description: 'Flavorful onions, essential for a variety of dishes.',
        plantingProcess: 'Plant onion sets or seeds in early spring or fall. Space sets about 4 inches apart and cover with soil.',
        nutrition: 'Good source of vitamin C, B vitamins, and potassium.',
        detailedDescription: 'Onions add flavor to many dishes and can be eaten raw or cooked. They have various health benefits including anti-inflammatory properties and are rich in antioxidants. Onions require well-drained soil and regular watering.'
    },
    {
        id: 6,
        name: 'Capsicum',
        img: 'https://images.pexels.com/photos/7017/food-peppers-kitchen-yum.jpg?auto=compress&cs=tinysrgb&w=600',
        price: 3.0,
        rating: 4.6,
        deliveryTime: '2 days',
        description: 'Colorful and crisp capsicums, great for salads and cooking.',
        plantingProcess: 'Start seeds indoors 8-10 weeks before the last frost; transplant outdoors after frost danger has passed.',
        nutrition: 'High in vitamins A and C; low in calories.',
        detailedDescription: "Capsicum (bell peppers) come in various colors like green, red, yellow, and orange. They are sweet when ripe and can be eaten raw or cooked. Capsicums are rich in vitamins A and C which support immune function."
    },
    {
       id :7, 
       name : "Lettuce", 
       img : "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?auto=compress&cs=tinysrgb&w=600", 
       price : 1.0, 
       rating : 4.4, 
       deliveryTime : "3 days",
       description : "Fresh and crunchy lettuce perfect for salads and sandwiches.",
       plantingProcess : "Sow seeds directly in the ground as soon as soil can be worked in spring.",
       nutrition : "Low in calories; rich in vitamins A and K.",
       detailedDescription : "Lettuce is a leafy green vegetable commonly used in salads but can also be added to sandwiches or wraps for crunchiness. It grows best in cooler temperatures."
   },
   {
       id :8, 
       name : "Spinach", 
       img : "https://images.pexels.com/photos/3298064/pexels-photo-3298064.jpeg?auto=compress&cs=tinysrgb&w=600", 
       price : 2.2, 
       rating : 4.7, 
       deliveryTime : "2 days",
       description : "Nutritious spinach great for salads smoothies cooking.",
       plantingProcess : "Sow seeds directly into the soil in early spring or fall.",
       nutrition : "High in iron calcium vitamins A C.",
       detailedDescription : "Spinach is a leafy green vegetable that is high in nutrients such as iron and calcium. It can be eaten raw or cooked and is often used in salads or smoothies."
   },
   {
       id :9, 
       name : "Peppers", 
       img : "https://images.pexels.com/photos/2893882/pexels-photo-2893882.jpeg?auto=compress&cs=tinysrgb&w=600", 
       price : 2.8, 
       rating : 4.5, 
       deliveryTime : "3 days",
       description : "Sweet spicy peppers perfect for adding flavor to dishes.",
       plantingProcess : "Start seeds indoors; transplant outside after frost danger has passed.",
       nutrition : "Rich in vitamins A C; low in calories.",
       detailedDescription : "Peppers come in various varieties from sweet to spicy and can be used fresh or cooked to enhance flavors of many dishes."
   },
   {
      id :10, 
      name : "Garlic", 
      img : "https://images.pexels.com/photos/1460862/pexels-photo-1460862.jpeg?auto=compress&cs=tinysrgb&w=600", 
      price : 0.5, 
      rating : 4.8, 
      deliveryTime : "1 day",
      description : "Aromatic garlic essential for enhancing the flavor of any dish.",
      plantingProcess : "Plant individual cloves in fall or early spring about 6 inches apart.",
      nutrition : "Contains compounds with medicinal properties; rich in manganese vitamin B6.",
      detailedDescription :"Garlic is not only a culinary staple but also has numerous health benefits including anti-inflammatory properties."
   },
   {
      id :11, 
      name : "Ginger", 
      img : "https://images.pexels.com/photos/1337585/pexels-photo-1337585.jpeg?auto=compress&cs=tinysrgb&w=600", 
      price : 1.0, 
      rating : 4.3, 
      deliveryTime : "3 days",
      description :"Fresh ginger perfect for adding a spicy kick to your recipes.",
      plantingProcess :"Plant ginger rhizomes in warm soil after all danger of frost has passed.",
      nutrition :"Contains gingerol which has anti-inflammatory properties; good source of magnesium.",
      detailedDescription :"Ginger is widely used as a spice but also offers medicinal benefits such as aiding digestion."
   },
   {
      id :12, 
      name :"Cucumbers", 
      img :"https://images.pexels.com/photos/2329440/pexels-photo-2329440.jpeg?auto=compress&cs=tinysrgb&w=600",  
      price :1.5 ,  
      rating :4 ,  
      deliveryTime :"2 days",
      description :"Cool refreshing cucumbers great for salads snacking.",
      plantingProcess :"Sow seeds directly into the ground after the last frost date; space plants about a foot apart.",
      nutrition :"Low calories high water content contains vitamin K.",
      detailedDescription :"Cucumbers are hydrating vegetables that can be eaten raw or pickled."
   },
   {
      id :13 ,  
      name :"Broccoli" ,  
      img :"https://images.pexels.com/photos/1634356/pexels-photo-1634356.jpeg?auto=compress&cs=tinysrgb&w=600" ,  
      price :2.5 ,  
      rating :4.7 ,  
      deliveryTime :"3 days" ,  
      description :"Nutritious broccoli perfect for steaming roasting stir-fries." ,  
      plantingProcess :"Start seeds indoors or sow directly outdoors in early spring; space plants about a foot apart." ,  
      nutrition :"High vitamins C K contains fiber." ,  
      detailedDescription :"Broccoli is a cruciferous vegetable known for its cancer-fighting properties."
   },
   {
     id:14,
     name:"Eggplant",
     img:"https://images.pexels.com/photos/321551/pexels-photo-321551.jpeg?auto=compress&cs=tinysrgb&w=600",
     price:2,
     rating:4,
     deliveryTime:"3 days",
     description:"Versatile eggplant great for grilling roasting frying.",
     plantingProcess:"Start seeds indoors or sow directly outdoors after frost danger has passed.",
     nutrition:"Good source of fiber vitamins B1 B6 potassium.",
     detailedDescription:"Eggplants are often used as meat substitutes due to their texture when cooked."
   },
   {
     id:15,
     name:"Radish",
     img:"https://images.pexels.com/photos/1257075/pexels-photo-1257075.jpeg?auto=compress&cs=tinysrgb&w=600",
     price:1,
     rating:4,
     deliveryTime:"2 days",
     description:"Crisp spicy radishes perfect for salads garnishes.",
     plantingProcess:"Sow seeds directly into the ground as soon as soil can be worked.",
     nutrition:"Low calories high vitamin C.",
     detailedDescription:"Radishes grow quickly making them ideal for beginner gardeners."
   },
   {
     id:16,
     name:"Sweet Potatoes",
     img:"https://images.pexels.com/photos/13059602/pexels-photo-13059602.jpeg?auto=compress&cs=tinysrgb&w=600",
     price:1.8,
     rating:4,
     deliveryTime:"3 days",
     description:"Sweet nutritious sweet potatoes great for baking roasting.",
     plantingProcess:"Plant slips outdoors after all danger of frost has passed.",
     nutrition:"High fiber vitamin A vitamin C.",
     detailedDescription:"Sweet potatoes are versatile tubers that can be used in both savory dishes and desserts."
   },
   {
     id:17,
     name:"Asparagus",
     img:"https://images.pexels.com/photos/351679/pexels-photo-351679.jpeg?auto=compress&cs=tinysrgb&w=600",
     price:3,
     rating:4,
     deliveryTime:"5 days",
     description:"Tender asparagus perfect for steaming grilling roasting.",
     plantingProcess:"Plant crowns outdoors in early spring after frost danger has passed.",
     nutrition:"Rich vitamins A C E K folate.",
     detailedDescription:"Asparagus takes several years to establish but rewards patience with delicious spears."
   },
   {
     id:18,
     name:"Mushrooms",
     img:"https://images.pexels.com/photos/74510/pexels-photo-74510.jpeg?auto=compress&cs=tinysrgb&w=600",
     price:2,
     rating:4,
     deliveryTime:"3 days",
     description:"Earthy mushrooms great for adding depth to your dishes.",
     plantingProcess:"Grow from spores or spawn on suitable substrate like straw or wood chips.",
     nutrition:"Low calorie source B vitamins selenium.",
     detailedDescription:"Mushrooms can enhance flavors significantly while providing unique textures."
   },
   {
    id: 19,
    name: "Cauliflower",
    img: "https://images.pexels.com/photos/4963755/pexels-photo-4963755.jpeg?auto=compress&cs=tinysrgb&w=600",
    price: 1.5,
    rating: 4.0,
    deliveryTime: "3 days",
    description: "Versatile cauliflower, perfect for roasting, mashing, and stir-fries.",
    plantingProcess: "Start seeds indoors or sow directly outdoors after frost danger has passed.",
    nutrition: "Rich in vitamins C, K, fiber, and antioxidants.",
    detailedDescription: "Cauliflower is often used as a low-carb substitute for grains and can be prepared in various ways, including steaming, roasting, or pureeing."
    },
    {
    id: 20,
    name: "Peas",
    img: "https://images.pexels.com/photos/255469/pexels-photo-255469.jpeg?auto=compress&cs=tinysrgb&w=600",
    price: 1.0,
    rating: 4.0,
    deliveryTime: "2 days",
    description: "Sweet and tender peas, great for adding to soups, stews, and salads.",
    plantingProcess: "Sow seeds directly into the ground as soon as the soil can be worked.",
    nutrition: "High in protein, fiber, vitamins A and C.",
    detailedDescription: "Peas are easy to grow and make an excellent choice for beginner gardeners. They can be eaten fresh or cooked and are a great addition to many dishes."
    }
];